//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaPayInterface.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://196.0.18.166/UraBnkPmtService/URAPayment.asmx")]
        public string OrientFCDBService_URAInterface_UraPmtService {
            get {
                return ((string)(this["OrientFCDBService_URAInterface_UraPmtService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://192.168.192.124:443/ecolSOAPServer/index.php")]
        public string OrientFCDBService_NSSFGateway_NSSFWSDL {
            get {
                return ((string)(this["OrientFCDBService_NSSFGateway_NSSFWSDL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ecitie.kcca.go.ug/api/bank-paymentv1.php")]
        public string AdaPayInterface_KCCAGateway_BankPaymentService {
            get {
                return ((string)(this["AdaPayInterface_KCCAGateway_BankPaymentService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://41.84.196.234:8098/umemebillinterface/EPayment.asmx")]
        public string AdaPayInterface_UMEMEGateway_EPayment {
            get {
                return ((string)(this["AdaPayInterface_UMEMEGateway_EPayment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mail.nwsc.co.ug/nwscbillinginterface/nwscbillinginterface.asmx")]
        public string AdaPayInterface_NWSCGateway_NWSCBillingInterface {
            get {
                return ((string)(this["AdaPayInterface_NWSCGateway_NWSCBillingInterface"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mail.nwsc.co.ug/nwscbillinginterface/nwscbillinginterface.asmx?wsdl")]
        public string OrientFCDBService_NWSCInterface_NWSCBillingInterface {
            get {
                return ((string)(this["OrientFCDBService_NWSCInterface_NWSCBillingInterface"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://41.84.196.234:8098/umemebillinterface/EPayment.asmx?wsdl")]
        public string OrientFCDBService_UMEMEGateway_EPayment {
            get {
                return ((string)(this["OrientFCDBService_UMEMEGateway_EPayment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ecitie.kcca.go.ug/api/bank-paymentv1.php?wsdl")]
        public string OrientFCDBService_KCCAGateway_BankPaymentService {
            get {
                return ((string)(this["OrientFCDBService_KCCAGateway_BankPaymentService"]));
            }
        }
    }
}
